# Generated by Django 3.0.3 on 2020-02-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_auto_20200215_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.Book'),
        ),
    ]
